apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealmIdentityProvider
metadata:
  name: id-gov-ua
spec:
  realm: id-gov-ua
  alias: idgovua
  authenticateByDefault: true
  enabled: true
  firstBrokerLoginFlowAlias: "custom-first-broker-login-feature"
  providerId: "idgovua"
  config:
    clientId: {{ .Values.idgovua.clientId }}
    clientSecret: {{ .Values.idgovua.clientSecret }}
    hideOnLoginPage: "true"
    dsoCertificateUrl: http://digital-signature-ops:8080/api/key/certificate
    dsoDecryptInfoUrl: http://digital-signature-ops:8080/api/key/decrypt
    sandbox: {{ .Values.idgovua.sandbox | squote }}
    syncMode: "IMPORT"
    useJwksUrl: "true"
