apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: master
  annotations:
    helm.sh/resource-policy: keep
spec:
  keycloakOwner: main
  realmName: master
  themes:
    adminConsoleTheme: keycloak
  realmEventConfig:
    adminEventsDetailsEnabled: true
    adminEventsEnabled: true
    eventsEnabled: true
    eventsExpiration: 15000
    eventsListeners:
      - jboss-logging
      - metrics-listener
