apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: web-console-keycloak-client
spec:
  clientId: web-console-keycloak-client
  directAccess: true
  clientRoles: null
  realmRoles: null
  protocolMappers: null
  targetRealm: openshift
  public: false
  webUrl: "https://oauth-openshift.{{ .Values.dnsWildcard }}/oauth2callback/keycloak"
