apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.nginx.name }}-proxy
  labels:
    app: {{ .Values.nginx.name }}-proxy
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.nginx.keycloak.mock }}
  port:
    targetPort: {{ .Values.nginx.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.nginx.name }}
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
