apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  identityProviders:
    - openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: web-console-keycloak-client
        clientSecret:
          name: keycloak-client-web-console-keycloak-client-secret
        issuer: >-
          [KEYCLOAK_URL]/auth/realms/openshift
      mappingMethod: add
      name: keycloak
      type: OpenID
